name: Stop non-prod apps overnight

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          az webapp stop --name job-app-britedge-staging-taisiia --resource-group britedge-uk-rg
          az webapp stop --name job-app-britedge-dev-taisiia --resource-group britedge-uk-rg